config/routes.rb
Rails.application.routes.draw do
  # Home controller (top-level) paths. index is our root.
  root 'home#index'
  get 'about', to: "home#about"
  get 'faq', to: "home#faq"

  # User signup/login/etc. paths via devise
  devise_for :users

  # User's page maps to their collection which is handled by index action in the images controller.
  get 'users/:id', to: 'images#index', as: 'user'
  resources :images, except: [:index]
  get 'images/addfroms3', to: 'images#new', as: 'new_image_from_s3'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/faq.rb
class Faq < ApplicationRecord
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :user

  before_save do
    self.latitude = self.latitude.to_f unless self.latitude.class == 'Float'
    self.longitude = self.longitude.to_f unless self.longitude.class == 'Float'

    # Make sure latitude is between -90 & 90 degrees
    if self.latitude < -90
      self.latitude = -90
    elsif self.latitude > 90
      self.latitude = 90
    end

    # Make sure longitude is between -180 & 180 degrees
    if self.longitude < -180
      self.longitude = -180
    elsif self.longitude > 180
      self.longitude = 180
    end

    if self.pictype == :picture
      self.pictype = 0
    elsif self.pictype == :artwork
      self.pictype = 1
    elsif self.pictype == :other
      self.pictype = 2
    else
      self.pictype = 0
    end

    # Make sure width & height are integers
    self.width = self.width.to_i unless self.width.class == 'Integer'
    self.height = self.height.to_i unless self.height.class == 'Integer'

    self.aspect_ratio = width.to_f / height.to_f

    # Filter unwanted characters from the tags
    self.tags.gsub!(/[^0-9a-zA-Z\-_\+=~\.\?\$;:'"@#\$%\^\&\*\(\)\[\]\{\}\\\/<>,]/,'')
  end

  enum pictype: [:picture, :artwork, :other]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :images, dependent: :destroy

  before_save { self.email.downcase! }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
		if(resource.is_a?(User))
			resource
		else
			super
		end
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

  def faq
    @faqs = Faq.all
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  # Must be logged in to create, edit or delete.
  before_action :authenticate_user!, except: [:index, :show]

  # index corresponds to a user's collection.
  def index
    @images = Image.where(user_id: params[:id])
    @user = User.find(params[:id])
  end

  def new
    @image = Image.new
  end

  def create
    @image = Image.new(image_params)
    @image.user = current_user
    if @image.save
      flash[:notice] = "Added image \"#{@image.title}\" to your collection!"
      redirect_to @image
    else
      flash[:alert] = "Couldn't save image \"#{@image.title}\". Please try again."
      render :new
    end
  end

  # show corresponds to a single image view.
  def show
    @image = Image.find(params[:id])
    @tags = @image.tags.split(',')
  end

  def edit
    @image = Image.find(params[:id])
  end

  def update
    @image = Image.find(params[:id])
    @image.assign_attributes(image_params)
    if @image.save
      flash[:notice] = "Image \"#{@image.title}\" updated successfully!"
      redirect_to @image
    else
      flash[:alert] = "Couldn't update image \"#{@image.title}\". Please try again."
      render :edit
    end
  end

  def destroy
    @image = Image.find(params[:id])
    if @image.destroy
      flash[:notice] = "Image \"#{@image.title}\" deleted."
      redirect_to current_user
    else
      flash[:alert] = "Couldn't delete image \"#{@image.title}\". Please try again."
      render :show
    end
  end

  private

  def image_params
    params.require(:image).permit(:title, :pictype, :uri, :latitude, :longitude, :width, :height, :tags)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
  # Given a collection's user & the current user, produces an appropriate title for the collection.
  def collection_title(user, current_user)
    (current_user == user ? "Your" : (user.name << "'s")) << " Collection"
  end

  # Gives a CSS class name based on the pictype
  def image_class(image)
    case image.pictype
    when :picture
      return "collectionImagePicture"
    when :artwork
      return "collectionImageArtwork"
    when :other
      return "collectionImageDefault"
    end
  end

  # Returns a size to pass to the image_tag function
  def image_small_size(aspect_ratio)
    max_width = 300
    max_height = 300
    size = ""
    if aspect_ratio < max_width/max_height
      # If the image in question is narrower than our defined box (smaller aspect ratio),
      # then use maximum height & scale the width to fit by multiplying the max width
      # by the aspect ratio.
      width = (max_width * aspect_ratio).floor
      size = "#{width}x#{max_height}"
    else
      # Otherwise, the image in question is wider than our defined box (larger aspect ratio),
      # so use maximum width & scale the height to fit by dividing the max height
      # by the aspect ratio.
      height = (max_height / aspect_ratio).floor
      size = "#{max_width}x#{height}"
    end
    size
  end

  def image_large_size(aspect_ratio)
    max_width = 800
    max_height = 800
    size = ""
    if aspect_ratio < max_width/max_height
      # If the image in question is narrower than our defined box (smaller aspect ratio),
      # then use maximum height & scale the width to fit by multiplying the max width
      # by the aspect ratio.
      width = (max_width * aspect_ratio).floor
      size = "#{width}x#{max_height}"
    else
      # Otherwise, the image in question is wider than our defined box (larger aspect ratio),
      # so use maximum width & scale the height to fit by dividing the max height
      # by the aspect ratio.
      height = (max_height / aspect_ratio).floor
      size = "#{max_width}x#{height}"
    end
    size
  end

  # Returns a string with the given latitude & longitude translated into degrees, minutes, seconds
  # notation. Rounds to the nearest arcsecond (accurate to within ~5 meters per WGS84 spec).
  def location_with_symbols(latitude, longitude)
    lat_dir = ""
    long_dir = ""
    if latitude < 0
      lat_dir = "S"
      latitude = latitude.abs
    else
      lat_dir = "N"
    end
    if longitude < 0
      long_dir = "W"
      longitude = longitude.abs
    else
      long_dir = "E"
    end
    latitude_string = "#{latitude.floor}° "
    longitude_string = "#{longitude.floor}° "
    lat_min = (latitude - latitude.floor) * 60
    long_min = (longitude - longitude.floor) * 60
    latitude_string << "#{lat_min.floor}′ "
    longitude_string << "#{long_min.floor}′ "
    lat_sec = ((lat_min - lat_min.floor) * 60).round
    long_sec = ((long_min - long_min.floor) * 60).round
    latitude_string << "#{lat_sec.floor}″ " << lat_dir
    longitude_string << "#{long_sec.floor}″ " << long_dir
    latitude_string + ", " + longitude_string
  end
end

app/views/home/about.html.erb
<h1>About Capstone</h1>
<p>This project is meant to be a one-stop shop for organizing pictures on across one's devices, whether they be photos, artworks, or any other type of picture. It is intended to keep track of files &amp; allow users to tag their pictures so that they can easily search/sort them. In addition, it will hopefully allow you to post your pictures directly to social media.</p>

app/views/home/faq.html.erb
<h1>Frequently Asked Questions</h1>
<% @faqs.each do |faq| %>
  <h2><%= faq.question %></h2>
  <p><%= faq.answer %></p>
<% end %>

app/views/home/index.html.erb
<h1>Capstone</h1>
<p>I am the capstone project of Alexander Gould for <%= link_to "bloc.io", "http://bloc.io" %></p>
<p><%= link_to "Sign up today!", new_user_registration_path %>

app/views/images/edit.html.erb
<h1>Update an image</h1>
<%= form_for @image do |f| %>
  <div class="input-group">
    <span class="input-group-addon" id="title-addon">Title</span>
    <%= f.text_field :title, autofocus: true, class: "form-control", aria: { describedby: "title-addon" } %><br />
  </div>

  <div class="input-group">
    <%= f.label :pictype %><br />
    <%= f.radio_button :pictype, :picture %>Picture
    <%= f.radio_button :pictype, :artwork %>Artwork
    <%= f.radio_button :pictype, :other %>Other<br />
  </div>

  <div class="input-group">
    <%= f.label :uri, "URL:" %>
    <%= f.text_field :uri, class: "form-control" %><br />
    <p class="formReqs">(cannot be blank)</p>
  </div>

  <div class="input-group">
    <%= f.label :latitude %>
    <%= f.number_field :latitude, step: "0.000001", class: "form-control" %><br />
    <p class="formReqs">(must be between -90 &amp; 90, up to 6 decimal places allowed)</p><br />
  </div>

  <div class="input-group">
    <%= f.label :longitude %>
    <%= f.number_field :longitude, step: "0.000001", class: "form-control" %><br />
    <p class="formReqs">(must be between -180 &amp; 180, up to 6 decimal places allowed)</p><br />
  </div>

  <div class="input-group">
    <%= f.label :width %>
    <%= f.number_field :width, class: "form-control" %><br />
  </div>

  <div class="input-group">
    <%= f.label :height %>
    <%= f.number_field :height, class: "form-control" %><br />
  </div>

  <div class="input-group">
    <%= f.label :tags %>
    <%= f.text_area :tags, class: "form-control" %><br />
    <p class="formReqs">(tags should be separated by commas. Accepted characters: letters, numbers, spaces, and -_+=~.?!:;'"@#$%^&amp;*()[]{}&lt;&gt;/\)</p><br />
  </div>

  <%= f.submit "Add Image", class: "btn btn-success" %>
<% end %>

app/views/images/index.html.erb
<h1><%= collection_title(@user, current_user) %></h1>
<% @images.each do |image| %>
  <div class="container">
    <a href="<%= image_path(image) %>">
      <%= image_tag image.uri, class: image_class(image), alt: image.title, size: image_small_size(image.aspect_ratio) %>
    </a>
  </div>
<% end %>
<%= link_to "Add a new image", new_image_path %>

app/views/images/new.html.erb
<h1>Add a new image to your collection</h1>
<%= form_for @image do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, autofocus: true %><br />

  <%= f.label :pictype %><br />
  <%= f.radio_button :pictype, :picture %>Picture
  <%= f.radio_button :pictype, :artwork %>Artwork
  <%= f.radio_button :pictype, :other %>Other<br />

  <%= f.label :uri, "URL:" %>
  <%= f.text_field :uri %><br />
  <p class="formReqs">(cannot be blank)</p><br />

  <%= f.label :latitude %>
  <%= f.number_field :latitude, step: "0.000001" %><br />
  <p class="formReqs">(must be between -90 &amp; 90, up to 6 decimal places allowed)</p><br />

  <%= f.label :longitude %>
  <%= f.number_field :longitude, step: "0.000001" %><br />
  <p class="formReqs">(must be between -180 &amp; 180, up to 6 decimal places allowed)</p><br />

  <%= f.label :width %>
  <%= f.number_field :width %><br />

  <%= f.label :height %>
  <%= f.number_field :height %><br />

  <%= f.label :tags %>
  <%= f.text_area :tags %><br />
  <p class="formReqs">(tags should be separated by commas. Accepted characters: letters, numbers, spaces, and -_+=~.?!:;'"@#$%^&amp;*()[]{}&lt;&gt;/\)</p><br />

  <%= f.submit %>
<% end %>

app/views/images/show.html.erb
<h1><%= @image.title %></h1>
<%= image_tag @image.uri, class: image_class(@image), alt: @image.title, size: image_large_size(@image.aspect_ratio) %>
<h3>Type:</h3>
<p><%= @image.pictype %></p>
<% if @image.pictype == :picture %>
  <h3>Location:</h3>
  <p><%= location_with_symbols(@image.latitude, @image.longitude) %></p>
<% end %>
<h3>Tags:</h3>
<div class="container">
  <% @tags.each do |tag,i| %>
    <div class="tag">
      <%= tag %>
    </div>
  <% end %>
</div>
<h3>Add or remove tag:</h3>
<%= form_for @image, remote: true do |f| %>
  <%= f.label :tags %>
  <%= f.text_area :tags %>
  <%= f.submit %>
<% end %>
<%= link_to "Edit this image", edit_image_path %><br />
<%= link_to "Delete this image X", @image, method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Capstone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-default">
        <div class="container">
          <div class="collapse navbar-collapse" id="navbar-collapse">
            <ul class="nav navbar-nav">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Capstone <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Home", root_path %></li>
                  <li><%= link_to "About", about_path %></li>
                  <li><%= link_to "FAQ", faq_path %></li>
                  <li role="separator" class="divider"></li>
                  <% if user_signed_in? %>
                    <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
                  <% else %>
                    <li><%= link_to "Sign In", new_user_session_path %></li>
                  <% end %>
                </ul>
              </li>
              <% if user_signed_in? %>
                <li><%= link_to "My Collection", current_user %></li>
                <li><%= link_to "Add New Image", new_image_path %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
      <% if flash[:notice]  %>
        <p class="notice" id="noticeDiv"><%= flash[:notice] %></p>
      <% end %>
      <% if flash[:alert] %>
        <p class="alert" id="alertDiv"><%= flash[:alert] %></p>
      <% end %>
    </header>
    <main>
      <%= yield %>
    </main>
  </body>
</html>